### ISSUE TITLE
Missing setup.py

### ISSUE THREAD

**Issue by alexis-via** [manuelRiel/invoice2data#2]
"Normal" users are used to install a Python module via:

```
sudo python ./setup.py install
```
We're lacking this file (and maybe others) to make it a standard python module.

**Comment by sebastienbeau** [comment]
To really close the issue we need to set the name/email of the maintainer of the package : https://github.com/akretion/invoice2data/blob/odoo-pdf-import/setup.py

And also to push this package on pypi
