### ISSUE TITLE
Missing licence information

### ISSUE THREAD

**Issue by alexis-via** [manuelRiel/invoice2data#4]
I didn't find any information about the "licence" of this great "invoice2data" lib. Did I miss something ?

I think it's important to choose a free software licence and display it clearly.

**Comment by alexis-via** [comment]
@manuelRiel We need your decision on this. You are the author, so you should decide under which licence you publish the code.

**Comment by manuelRiel** [comment]
On it. I'll read up on the topic. Will be BSD or something else that's easy to work with in business environments.

**Comment by alexis-via** [comment]
OK, great !
