### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by manuelRiel** [manuelRiel/invoice2data#6]

**Comment by alexis-via** [comment]
The big problem we have for tests is that invoices very often contain confidential information. Of course, we ca, do PDF editing to anonymize the invoices, but it's a painful work and we won't do that for each supplier.

I don't have the "magic" idea to solve that... My only idea would be to setup a confidential repository that would contain the invoices and in which we would run the tests, but it means setting up a private test plateform ; we can't use the free Travis/Github option.

**Comment by manuelRiel** [comment]
I had the same issue with projects before. Solved it with env vars on CircleCI. So nothing becomes public. The samples are downloaded when the tests are run and accessible with a password. Will add that today.

**Comment by manuelRiel** [comment]
Adding tests for Python 3 and 2 on CircleCi. Optionally download custom PDFs from hidden location.

**Comment by manuelRiel** [comment]
Added bin-installation. So now it's just:

`invoice2data invoice2data/test/pdfs/2014-08*`

**Comment by manuelRiel** [comment]
Setup tests and badge in README.md
